### PR TITLE
Add sass utils for faster development.

### PR DESCRIPTION
**Pull request by timrijkse**
Update contains:

Mixins:
- aspect-ratio: Maintain Aspect Ratio Mixin. The mixin assumes you'll be nesting an element with the class of content inside your initial block.
- font-face: font-face helper. Be sure to have the following font files: eot, woff, ttf, svg. Font can be generated at https://www.fontsquirrel.com/tools/webfont-generator
- placeholder: cross-browser :placeholder styles. Automatically adds all needed vendor prefixes.

Functions:
- ease: CSS easings based on ceaser. https://matthewlein.com/ceaser/
- respond-to: Media query helper. Helps you to have consistent breakpoints.
- zindex: Better z-index managing. Create a list of element names and get the z-index based on elements name. Returns a number.

Extends:
- clearfix: Clearfix, For clearing floats like a boss. See http://h5bp.com/q
- force-hardware: Sets transform and backface-visiblity which forces hardware acceleration.
- reset-bmp: Resets border, margin and padding
- reset-input: Remove all default browser input styles.
- reset-list: Reset ul element. Removes list-style and extends %reset-bmp.
- transform-center: Absolute element. Positioned in center horizontally and vertically.
- unstyled-link: A link that looks and acts like the text it is contained within.

### CODE REVIEW

**Comment by timrijkse** [comment]
Preview of the utils doc: http://dev.hoasting.net/cssdocs/section-utils.html

**Comment by petervmeijgaard** [comment]
I think this will bloat the boilerplate a bit too much.
I know I won't use most of the utilities. Perhaps a `support` or `utils` repository will suffice?

**Comment by timrijkse** [comment]
True about bloating the boilerplate. Still was curious about your opinion. 

For me these utils are really useful in almost every client project. This also is the reason why I've created a blocklevel branch (for now) because I want to have a quick vueture setup with a blocklevel taste without the need to install things separately.

Do you have any idea about a good way to make these utils optional? A seperate repository would work, is this something which can be achieved with git submodules? I'm not that familiar with that.

**Comment by petervmeijgaard** [comment]
It is possible to create a separate `npm` package for utilities that aren't required by default.

In you stylesheet you can import the css:
`@import "~vueture-utils/sass/utils.scss";`

Or something like this...

This way you can specify which utilities are useful and which aren't.
Same goes for JavaScript by the way.

**Comment by petervmeijgaard** [comment]
And this way you can also create a custom package for Blocklevel.
So you can create a `blocklevel-vueture-utils`-package and require that one inside your projects.

**Comment by timrijkse** [comment]
Removed utils from boilerplate. Moved to seperate repository: https://github.com/Blocklevel/vueture-blocklevel-sass-utils/

**Docs:**
https://github.com/Blocklevel/vueture-blocklevel-sass-utils/blob/master/README.md

**Pull request closed without merging**
